sonar.projectKey=cloudshop
sonar.projectName=CloudShop
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.token=sqp_53748d0853be052b3249e9e383a7a2a6ccd4375a

sonar.exclusions=**/.terraform/**,**/*.tfstate,**/.git/**,**/node_modules/**
